### ISSUE TITLE
Help with Venn diagrams

### ISSUE THREAD

**Issue by mnr006** [Bucknell-Biol364/RNASeqProject#10]
https://github.com/Bucknell-Biol364/RNASeqProject/blob/88440d05573b7e875547a848c3ded4f5b57168a7/FinalReport/Table_generation.Rmd#L12

@ianvogel @KateBille @jfberhane 
Worked on this for about 2 hours, had to go back and fix several tables that had duplicates and other issues. I'm kind of stuck on how to proceed with the Venn diagrams. I started work as you can see, but getting an error I'm not sure what to do with about impossible areas...
I'm also unsure if I'm calculating the shared counts right- so if someone could double check them. I think the pairs are fine, but the one triple comparison that may not be 0 doesn't look right.

**Comment by KateBille** [comment]
I think we want the number of duplicates in the new groups instead of the
number of distinct ones. I think (could be wrong) that command just calls a
list of the unique names in the column, but does not represent that it is
only in the list one time. I can work on this tomorrow and will let you
know if I figure it out!

**Comment by KField-Bucknell** [comment]
Here is some code that I have used to make Venn Diagrams. I will add the csv files to the repo so that you can test it out.
```{r}
# Load packages
if (!require("VennDiagram")) install.packages("VennDiagram"); library(VennDiagram)
if (!require("readr")) install.packages("readr"); library(readr)

# Read tables
Epfu.Mylu.UP <- read_table2("tables/EPUNvsEPIN.up.txt")
Epfu.Mylu.DOWN <- read_table2("tables/EPUNvsEPIN.down.txt")

Mylu.Mylu.UP <- read_table2("tables/MYINvsMYUN.down.txt")
Mylu.Mylu.DOWN <- read_table2("tables/MYINvsMYUN.up.txt")

# Make venn diagram
venn.diagram(list(MyluDown = Mylu.Mylu.DOWN$Id, EpfuDown = Epfu.Mylu.DOWN$Id, 
                  MyluUp = Mylu.Mylu.UP$Id, EpfuUp = Epfu.Mylu.UP$Id), 
             fill = c("cornflowerblue", "green", "yellow", "darkorchid1"), 
             alpha = c(0.5, 0.5, 0.5, 0.5), cex = 2, lwd = 0,
             cat.fontface = 4,lty =2, filename="MyluVsEpfu.edgeR.mylu.png", imagetype="png")
```

**Comment by mnr006** [comment]
I spent the morning on this- and I think I figured something out actually! This code looks interesting though if someone else wants to test it out, to see if we can make better Venn diagrams!

**Comment by jfberhane** [comment]
I tried the code and there were a couple errors that I was able to work through so I made the proper code adjustments

I also made some plots with the VennDiagram package. The whole error about impossible negative areas is really irritating. It took me a while but I was able to figure out how to calculate the correct areas, but I needed to pull those numbers from the diagrams you guys already made with the venn package. The VennDiagram package lets you use color which is nice, but the way they do triple plots doesn't look great because the circles are arranged horizontally instead of in a triangle formation like you expect. And for some reason the code I made pops out two plots: one with a title and one without. If we actually wanted to use the color Venn diagrams then we might need to export the plot with title as a png and then include each graphic.

**Comment by KateBille** [comment]
I saved the color plots as pngs and then made two "mega" plots which combine the aligner images in one and the de images in another. I created a new file called "venn_figs" in the "FinalReport" folder which has the individual plots as png's and the combination plots as png's. If we want to play around with the formatting of individual plots that is still possible, just run the combo plots code at the end to update them. 

Not sure how it looks on your computers, but I'd like to look at the combo plots on a screen that is larger than mine, because it looks like the titles may be difficult to read.
